mkarchiso_task:
  container:
    cpu: 8
    memory: 16G
    image: archlinux:latest
  prepare_mkarchiso_script:
    - pacman-key --init
    - echo ' ' >> /etc/pacman.conf
    - echo '[multilib]' >> /etc/pacman.conf
    - echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
    - pacman --noconfirm -Sy xdotool
    - pacman-key --recv-key FBA220DFC880C036
    - pacman-key --lsign-key FBA220DFC880C036
    - pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
    - echo ' ' >> /etc/pacman.conf
    - echo '[chaotic-aur]' >> /etc/pacman.conf
    - echo 'Include = /etc/pacman.d/chaotic-mirrorlist' >> /etc/pacman.conf
    
    # Hybrid Linux Repo Mirrorlist
    - pacman -U 'https://osdn.net/projects/hybridlinux/storage/hl-core/x86_64/hybrid-mirrorlist-20220920-1-x86_64.pkg.tar.zst'
    
    # HL-Additions Repo
    - echo ' ' >> /etc/pacman.conf
    - echo '[hl-additions]' >> /etc/pacman.conf
    - echo 'Include = /etc/pacman.d/hybrid-mirrorlist' >> /etc/pacman.conf
    
    # HL-Core
    - echo ' ' >> /etc/pacman.conf
    - echo '[hl-core]' >> /etc/pacman.conf
    - echo 'Include = /etc/pacman.d/hybrid-mirrorlist' >> /etc/pacman.conf
    
    # HL-Drivers
    - echo ' ' >> /etc/pacman.conf
    - echo '[hl-drivers]' >> /etc/pacman.conf
    - echo 'Include = /etc/pacman.d/hybrid-mirrorlist' >> /etc/pacman.conf
    
    # HL-Firmware
    - echo ' ' >> /etc/pacman.conf
    - echo '[hl-firmware]' >> /etc/pacman.conf
    - echo 'Include = /etc/pacman.d/hybrid-mirrorlist' >> /etc/pacman.conf
    
    # HL-Kernel
    - echo ' ' >> /etc/pacman.conf
    - echo '[hl-kernel]' >> /etc/pacman.conf
    - echo 'Include = /etc/pacman.d/hybrid-mirrorlist' >> /etc/pacman.conf
    
    # HL-Multilib
    - echo ' ' >> /etc/pacman.conf
    - echo '[hl-multilib]' >> /etc/pacman.conf
    - echo 'Include = /etc/pacman.d/hybrid-mirrorlist' >> /etc/pacman.conf
    
    # HL-Soft
    - echo ' ' >> /etc/pacman.conf
    - echo '[hl-soft]' >> /etc/pacman.conf
    - echo 'Include = /etc/pacman.d/hybrid-mirrorlist' >> /etc/pacman.conf
    
    # Add User
    - sh -c 'useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers'
    - chown user -R ..
    - chown user -R /tmp
    - pacman -Syy --noconfirm git archiso micro bash
    
  build_script:
    - git clone https://github.com/Hybrid-Project-Developers/hybrid-linux-archiso
    - su user -c "mkarchiso -v -w /hybrid-work-dir -o /hybrid-iso-out /hybrid-linux-archiso"
    
    
